### PR TITLE
Migrate to use v1 API

### PR DESCRIPTION
**Pull request by cosmo0920**
To simplify plugin implementation, we can use timer plugin helper to
reduce raw cool.io timer pattern.

### CODE REVIEW

**Comment by niyonmaruz** [comment]
I'm going to check in 24h. Thanks!

**Comment by niyonmaruz** [comment]
@cosmo0920 I'm going to check in 24h. Thanks!

**Comment by niyonmaruz** [comment]
@cosmo0920 I've checked codes and operation and I confirmed there is no problem.
I uploaded new package to Rubygems.
https://rubygems.org/gems/fluent-plugin-osquery/versions/0.0.3
Thank you!

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
